# Generated by Django 2.2 on 2023-02-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
