# Generated by Django 2.2 on 2023-02-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_api', '0002_auto_20230208_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
